### ISSUE TITLE
Name change

### ISSUE THREAD

**Issue by qmatic0** [nksupermarket/Ether#3]
I've noticed you've changed your github name so the old link to the start page doesn't work anymore.  Changing the link to your new name works but my settings are all gone. Is there a way to get my settings back or do I just have to redo all of my links? Thanks!

**Comment by nksupermarket** [comment]
Apologies. You can get your settings back Let me figure out the best way to
do it and I'll get back to you.

**Comment by nksupermarket** [comment]
Thanks for your patience. I had to fix a couple of bugs as well but everything looks good now and you can get your settings back by following these steps:

1) go to https://lookingcoolonavespa.github.io/Ether
2) open your developer tools by pressing `Ctrl + Shift + I` 
3) go to the `console` tab
4) copy and paste this code into the input 
```
const config = [
  "keybinds",
  "links",
  "theme",
  "image",
  "search",
  "custom search details",
].reduce((acc, curr) => {
  return { ...acc, [curr]: JSON.parse(localStorage.getItem(curr)) };
}, {});
JSON.stringify(config, null, 0);
```
5) copy everything inside the single quotes eg. 'copy everything inside here' <-- just the text 
6) go to https://nksupermarket.github.io/Ether and go to the settings
7) scroll down `import json`, paste everything there and save

**Comment by qmatic0** [comment]
Thank you so much it worked perfectly. Your instructions are so clear and concise!
